version: '3.7'
services:
  server:
    build: ./
    container_name: cloudstorage_server
    environment:
      spring.datasource.url: jdbc:postgresql://database:5432/postgres
      spring.jpa.hibernate.ddl-auto: update
    ports:
      - "8081:8081"
    depends_on:
      - database
  database:
    image: postgres
    container_name: cloudstorage_db
    environment:
      POSTGRES_USER: barbarisssss
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432"